name: statistics
description: Statistics package for easy and efficient data manipulation with built-in Bayesian Network (Bayes Net), many mathematical functions and tools.
version: 1.2.1
homepage: https://github.com/gmpassos/statistics

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  intl: ^0.20.2
  collection: ^1.19.0
  data_serializer: ^1.2.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.28.0
  dependency_validator: ^3.2.3
  coverage: ^1.15.0

#dependency_overrides:
#  data_serializer:
#    path: ../data_serializer

